@baseURL = http://localhost:3000
@token = COLE_SEU_TOKEN_AQUI


### Listar adoções (admin)

GET {{baseURL}}/adoptions
Authorization: Bearer {{token}}

### Adotar pet disponível (adopter)

POST {{baseURL}}/adoptions
Authorization: Bearer {{token}}
Content-Type: application/json

{
"petId": 3
}