@baseURL = http://localhost:3000
@token = COLE_SEU_TOKEN_AQUI

# ---- /PETS ----

# --- Rotas Públicas ---

# Lista todos os pets com status "available" para adoção
GET {{baseURL}}/pets/available

###

# --- Rotas Protegidas (Admin) ---

# Listar todos os pets
GET {{baseURL}}/pets
Authorization: Bearer {{token}}

###

# Buscar pet por ID
GET {{baseURL}}/pets/1
Authorization: Bearer {{token}}

###

# Buscar pet inexistente
GET {{baseURL}}/pets/999
Authorization: Bearer {{token}}

###

# Criar pet
POST {{baseURL}}/pets
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name": "Thor",
"age": 2,
"species": "dog",
"size": "large",
"description": "Golden Retriever muito brincalhão e amigável"
}

###

# Atualizar pet
PUT {{baseURL}}/pets/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name": "Thor Atualizado",
"age": 3,
"species": "dog",
"size": "large",
"description": "Muito dócil"
}

###

# Tentar alterar status manualmente
PUT {{baseURL}}/pets/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name": "Thor",
"age": 2,
"species": "dog",
"size": "large",
"status": "adopted",
"description": "Golden Retriever muito brincalhão e amigável"
}

###

# Excluir pet disponível
DELETE {{baseURL}}/pets/1
Authorization: Bearer {{token}}

###

# Excluir pet adotado
DELETE {{baseURL}}/pets/2
Authorization: Bearer {{token}}

###